version: '3'
services:
  postgres:
    image: "postgres"
    restart: always
    env_file:
      - ./env/dev/database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  cassandra:
      image: cassandra:latest
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - cassandra_data:/var/lib/cassandra
  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:latest
      depends_on:
        - cassandra
      volumes:
        - ./src/main/resources/cassandra_schema.cql:/schema.cql 
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
  grafana:
    image: grafana/grafana:7.3.7
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.docker.localhost`)"
    expose:
      - "3000"
    user: "104"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./service_configs/grafana/dash_boards:/etc/grafana/provisioning/dashboards
      - ./service_configs/grafana/data_sources:/etc/grafana/provisioning/datasources
    env_file: 
      - ./env/dev/grafana.env
  reverse-proxy:
    image: traefik:v2.4
    restart: always
    command: --configFile=/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./service_configs/traefik/certs:/certs
      - ./service_configs/traefik/traefik.toml:/etc/traefik/traefik.toml
  influxdb:
    image: influxdb:latest
    restart: always
    env_file:
      - ./env/dev/influxdb.env
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./service_configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./service_configs/influxdb/init:/docker-entrypoint-initdb.d
  kafka:
    image: confluentinc/cp-kafka:5.4.1
    restart: always
    ports:
      - "9093:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LOG_DIRS=/logs
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2182
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29094,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - kafka-logs:/logs
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    restart: always
    ports:
      - "9182:2182"
    volumes:
      - zookeeper-data:/datalog
    environment:
      - ZOOKEEPER_CLIENT_PORT=2182
volumes:
  database-data:
  kafka-logs:
  zookeeper-data:
  influxdb-data:
  grafana_data:
  cassandra_data:
